export const demoProducts = [
  {id:'demo-1',sku:'UrbanCart-TEE-001',name:'Essential Heavyweight Tee',brand:'UrbanCart',category:'Clothing',subcategory:'T-Shirts',gender:'Men',price:1499,compare_at_price:1999,image_url:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',description:'Premium heavyweight cotton tee with a relaxed fit.',sizes:['S','M','L','XL'],colors:['Black','White','Stone'],rating:4.7,review_count:184},
  {id:'demo-2',sku:'UrbanCart-HOOD-002',name:'Core Oversized Hoodie',brand:'UrbanCart',category:'Clothing',subcategory:'Hoodies',gender:'Unisex',price:2999,compare_at_price:3999,image_url:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',description:'Soft fleece hoodie built for everyday layering.',sizes:['S','M','L','XL'],colors:['Black','Grey','Olive'],rating:4.8,review_count:231},
  {id:'demo-3',sku:'UrbanCart-DNM-003',name:'Relaxed Straight Jeans',brand:'UrbanCart',category:'Clothing',subcategory:'Jeans',gender:'Men',price:3499,compare_at_price:4499,image_url:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80',description:'Straight-leg denim with a relaxed modern silhouette.',sizes:['30','32','34','36'],colors:['Indigo','Washed Black'],rating:4.5,review_count:98},
  {id:'demo-4',sku:'UrbanCart-DRS-004',name:'Satin Slip Dress',brand:'UrbanCart',category:'Clothing',subcategory:'Dresses',gender:'Women',price:3999,compare_at_price:5499,image_url:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=80',description:'Minimal satin dress designed for effortless evenings.',sizes:['XS','S','M','L'],colors:['Black','Champagne','Burgundy'],rating:4.6,review_count:77},
  {id:'demo-5',sku:'UrbanCart-SNK-005',name:'Velocity Runner',brand:'NOVA',category:'Shoes',subcategory:'Running',gender:'Unisex',price:6999,compare_at_price:8999,image_url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',description:'Lightweight everyday runner with responsive cushioning.',sizes:['7','8','9','10','11'],colors:['White','Black','Red'],rating:4.8,review_count:342},
  {id:'demo-6',sku:'UrbanCart-SNK-006',name:'Court Low Classic',brand:'NOVA',category:'Shoes',subcategory:'Sneakers',gender:'Unisex',price:5499,compare_at_price:6999,image_url:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80',description:'Clean low-top sneaker with a timeless court profile.',sizes:['7','8','9','10','11'],colors:['White','Cream','Black'],rating:4.7,review_count:256},
  {id:'demo-7',sku:'UrbanCart-JKT-007',name:'Utility Overshirt',brand:'UrbanCart',category:'Clothing',subcategory:'Jackets',gender:'Men',price:4499,compare_at_price:5999,image_url:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80',description:'Structured utility overshirt with multiple pockets.',sizes:['S','M','L','XL'],colors:['Khaki','Black','Navy'],rating:4.4,review_count:54},
  {id:'demo-8',sku:'UrbanCart-BAG-008',name:'Studio Crossbody',brand:'NOVA',category:'Accessories',subcategory:'Bags',gender:'Women',price:2499,compare_at_price:3299,image_url:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',description:'Compact crossbody bag with an adjustable strap.',sizes:['One Size'],colors:['Black','Tan'],rating:4.6,review_count:120},
  {id:'demo-9',sku:'UrbanCart-CAP-009',name:'Minimal Logo Cap',brand:'UrbanCart',category:'Accessories',subcategory:'Caps',gender:'Unisex',price:999,compare_at_price:1299,image_url:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',description:'Low-profile cotton cap with a minimal embroidered logo.',sizes:['One Size'],colors:['Black','Cream','Green'],rating:4.5,review_count:66},
  {id:'demo-10',sku:'UrbanCart-TOP-010',name:'Ribbed Everyday Top',brand:'UrbanCart',category:'Clothing',subcategory:'Tops',gender:'Women',price:1799,compare_at_price:2299,image_url:'https://images.unsplash.com/photo-1506629905607-d9b1a5eec5c9?auto=format&fit=crop&w=900&q=80',description:'Soft ribbed top with a flattering everyday fit.',sizes:['XS','S','M','L'],colors:['Black','White','Mocha'],rating:4.6,review_count:83}
]
